# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-latest' 
  
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Docker version:"
        docker --version

        echo "Docker Compose version:"
        docker compose version

        echo "Working Dir: $SYSTEM_DEFAULTWORKINGDIRECTORY"
        ls -la "$SYSTEM_DEFAULTWORKINGDIRECTORY"

        cd "$SYSTEM_DEFAULTWORKINGDIRECTORY/UIAutomationProject"
        ls -la  # show files here to confirm docker-compose.yml exists

        echo "Running docker compose up"
        docker compose -f docker-compose.yml up -d

    - task: UseDotNet@2
      displayName: 'Install .NET 6 SDK'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'

    - script: |
        cd "$SYSTEM_DEFAULTWORKINGDIRECTORY/UIAutomationProject"
        dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory test-results
      displayName: 'Build & Run Tests'

    - script: |
        cd "$SYSTEM_DEFAULTWORKINGDIRECTORY/UIAutomationProject"
        docker compose down
      displayName: 'Tear Down Grid'
      condition: always()

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/test-results/*.trx'
        testRunTitle: 'Selenium UI Tests'
      condition: succeededOrFailed()
      displayName: 'Publish Test Results'
